### ISSUE TITLE
in big sur , install is error

### ISSUE THREAD

**Issue by iT-Boyer** [sindresorhus/alfred-xcode#4]
`sudo npm install --global alfred-xcode`

```ruby
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/alfred-xcode
npm ERR! command failed
npm ERR! command sh -c alfy-init
npm ERR! Error: Command failed: alfred-link
npm ERR! You are not allowed to run this app with root permissions.
npm ERR! If running without sudo doesn't work, you can either fix your permission problems or change where npm stores global packages by putting ~/npm/bin in your PATH and running:
npm ERR! npm config set prefix ~/npm
npm ERR!
npm ERR! See: https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md
npm ERR!
npm ERR!
npm ERR!     at makeError (/usr/local/lib/node_modules/alfred-xcode/node_modules/execa/index.js:174:9)
npm ERR!     at /usr/local/lib/node_modules/alfred-xcode/node_modules/execa/index.js:278:16
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:93:5) {
npm ERR!   code: 77,
npm ERR!   stdout: '',
npm ERR!   stderr: 'You are not allowed to run this app with root permissions.\n' +
npm ERR!     "If running without sudo doesn't work, you can either fix your permission problems or change where npm stores global packages by putting ~/npm/bin in your PATH and running:\n" +
npm ERR!     'npm config set prefix ~/npm\n' +
npm ERR!     '\n' +
npm ERR!     'See: https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md\n',
npm ERR!   failed: true,
npm ERR!   signal: null,
npm ERR!   cmd: 'alfred-link',
npm ERR!   timedOut: false,
npm ERR!   killed: false
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jhmac/.npm/_logs/2020-11-23T11_12_02_145Z-debug.log
```

**Comment by sindresorhus** [comment]
The error says it all. Don't use npm with `sudo`.

**Comment by iT-Boyer** [comment]
this error when without `sudo` :
 npm install --global alfred-xcode
```
npm ERR! code EACCES
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/alfred-xcode
npm ERR! dest /usr/local/lib/node_modules/.alfred-xcode-6uQ0neT2
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/alfred-xcode' -> '/usr/local/lib/node_modules/.alfred-xcode-6uQ0neT2'
npm ERR!  [Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/alfred-xcode' -> '/usr/local/lib/node_modules/.alfred-xcode-6uQ0neT2'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rename',
npm ERR!   path: '/usr/local/lib/node_modules/alfred-xcode',
npm ERR!   dest: '/usr/local/lib/node_modules/.alfred-xcode-6uQ0neT2'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jhmac/.npm/_logs/2020-11-24T01_18_13_306Z-debug.log
```
